stages:
  get_webpages:
    cmd:
      - python gather-clean-scripts/hyperlinks.py gather-clean-scripts/intermediates/saved_hyperlinks.txt
    deps:
      - gather-clean-scripts/hyperlinks.py
    outs:
      - gather-clean-scripts/intermediates/saved_hyperlinks.txt
  get_listings:
    cmd:
      - python gather-clean-scripts/get_yacht_classifieds.py gather-clean-scripts/intermediates/saved_hyperlinks.txt gather-clean-scripts/intermediates/raw_listings.csv
    deps:
      - gather-clean-scripts/intermediates/saved_hyperlinks.txt
      - gather-clean-scripts/hyperlinks.py
      - gather-clean-scripts/get_yacht_classifieds.py
    outs:
      - gather-clean-scripts/intermediates/raw_listings.csv
  clean:
    cmd:
      - python gather-clean-scripts/clean.py gather-clean-scripts/intermediates/raw_listings.csv gather-clean-scripts/intermediates/listings.csv -dn True
    deps:
      - gather-clean-scripts/clean.py
      - gather-clean-scripts/get_yacht_classifieds.py
      - gather-clean-scripts/hyperlinks.py
      - gather-clean-scripts/intermediates/raw_listings.csv
      - gather-clean-scripts/intermediates/saved_hyperlinks.txt
    outs:
      - gather-clean-scripts/intermediates/listings.csv
  remove_outliers:
    cmd:
      - python gather-clean-scripts/remove_outliers.py gather-clean-scripts/intermediates/listings.csv ./data/listings_wo_outliers.csv
    deps:
      - gather-clean-scripts/clean.py
      - gather-clean-scripts/get_yacht_classifieds.py
      - gather-clean-scripts/hyperlinks.py
      - gather-clean-scripts/intermediates/raw_listings.csv
      - gather-clean-scripts/intermediates/saved_hyperlinks.txt
      - gather-clean-scripts/intermediates/listings.csv
    outs:
      - data/listings_wo_outliers.csv
