stages:
  get_webpages:
    cmd:
      - python data_wrangling/hyperlinks.py data_wrangling/intermediates/saved_hyperlinks.txt
    deps:
      - data_wrangling/hyperlinks.py
    outs:
      - data_wrangling/intermediates/saved_hyperlinks.txt
  get_listings:
    cmd:
      - python data_wrangling/get_yacht_classifieds.py data_wrangling/intermediates/saved_hyperlinks.txt data_wrangling/intermediates/raw_listings.csv
    deps:
      - data_wrangling/intermediates/saved_hyperlinks.txt
      - data_wrangling/get_yacht_classifieds.py
    outs:
      - data_wrangling/intermediates/raw_listings.csv
  get_additional_features:
    cmd:
      - python data_wrangling/gather_additional_features.py data_wrangling/intermediates/saved_hyperlinks.txt data_wrangling/intermediates/additional_features_dataset.csv
    deps:
      - data_wrangling/intermediates/saved_hyperlinks.txt
      - data_wrangling/gather_additional_features.py
    outs:
      - data_wrangling/intermediates/additional_features_dataset.csv
  combine_additional_features:
    cmd:
      - python data_wrangling/combine_additional_features.py data_wrangling/intermediates/raw_listings.csv data_wrangling/intermediates/additional_features_dataset.csv data_wrangling/intermediates/raw_combined_dataset.csv
    deps:
      - data_wrangling/intermediates/raw_listings.csv
      - data_wrangling/intermediates/additional_features_dataset.csv
      - data_wrangling/combine_additional_features.py
    outs:
      - data_wrangling/intermediates/raw_combined_dataset.csv
  clean:
    cmd:
      - python data_wrangling/clean.py data_wrangling/intermediates/raw_combined_dataset.csv data_wrangling/intermediates/combined_dataset.csv -dn True
    deps:
      - data_wrangling/intermediates/raw_combined_dataset.csv
      - python data_wrangling/clean.py
    outs:
      - data_wrangling/intermediates/combined_dataset.csv
  remove_outliers:
    cmd:
      - python data_wrangling/remove_outliers.py data_wrangling/intermediates/combined_dataset.csv ./data/dataset_wo_outliers.csv
    deps:
      - data_wrangling/intermediates/combined_dataset.csv
      - data_wrangling/remove_outliers.py
    outs:
      - data/dataset_wo_outliers.csv
  train:
    cmd:
      - python data_modeling/train.py ./data/dataset_wo_outliers.csv data_modeling/trained_model.pkl -v
    deps:
      - data/dataset_wo_outliers.csv
      - data_modeling/train.py
    outs:
      - data_modeling/trained_model.pkl  
  predict:
    cmd: 
      - python data_modeling/predict.py Year, Length, Beam, Draft, Cabins, Is_Mono, Is_Diesel, Is_Cutter, Is_Ketch, Is_masthead_sloop, Is_Excellennt, Is_Fair, Is_Good, Is_project_boat, Engine_Count, Is_Inboard, Year_Listed, Is_Cruiser, Is_Daysailer data_modeling/trained_model.pkl
    deps:
      - data_modeling/trained_model.pkl
      - python data_modeling/predict.py
