stages:
  get_webpages:
    cmd:
      - python data_wrangling/hyperlinks.py data_wrangling/intermediates/saved_hyperlinks.txt
    deps:
      - data_wrangling/hyperlinks.py
    outs:
      - data_wrangling/intermediates/saved_hyperlinks.txt
  get_listings:
    cmd:
      - python data_wrangling/get_yacht_classifieds.py data_wrangling/intermediates/saved_hyperlinks.txt data_wrangling/intermediates/raw_listings.csv
    deps:
      - data_wrangling/intermediates/saved_hyperlinks.txt
      - data_wrangling/hyperlinks.py
      - data_wrangling/get_yacht_classifieds.py
    outs:
      - data_wrangling/intermediates/raw_listings.csv
  clean:
    cmd:
      - python data_wrangling/clean.py data_wrangling/intermediates/raw_listings.csv data_wrangling/intermediates/listings.csv -dn True
    deps:
      - data_wrangling/clean.py
      - data_wrangling/get_yacht_classifieds.py
      - data_wrangling/hyperlinks.py
      - data_wrangling/intermediates/raw_listings.csv
      - data_wrangling/intermediates/saved_hyperlinks.txt
    outs:
      - data_wrangling/intermediates/listings.csv
  remove_outliers:
    cmd:
      - python data_wrangling/remove_outliers.py data_wrangling/intermediates/listings.csv ./data/listings_wo_outliers.csv
    deps:
      - data_wrangling/clean.py
      - data_wrangling/get_yacht_classifieds.py
      - data_wrangling/hyperlinks.py
      - data_wrangling/intermediates/raw_listings.csv
      - data_wrangling/intermediates/saved_hyperlinks.txt
      - data_wrangling/intermediates/listings.csv
    outs:
      - data/listings_wo_outliers.csv
